### ISSUE TITLE
Mudança de página com class="collapse"

### ISSUE THREAD

**Issue by ghost** [borgesogato/gaticeHTML#1]
Eu to tentando linkar as paginas todas e criar meios provisórios para poder navegar dentro do app, mas só que empaquei completamente com o modo que a navegação funciona. Saquei que cada seção tem que ter a classe collapse e um id único, e que posso definir <a> e <button> com data-toggle="collapse" e com o devido data-target para navegar entre as telas. Mas a partir de todas as novas telas que eu criei, ele simplesmente não obedece, tentei testar com algumas telas antigas e apenas a section enroll funciona como "link", já a section cadastrar não vai, nem a section cats quando quero criar um objeto para voltar.

Tem alguma ideia como posso resolver isso?

**Comment by integrationarchitect** [comment]
Vc fez tudo certo, só que além disso vc precisava ter adicionado no arquivo main.js para esconder a tela da lista de gatos com o trecho q segue 

```
$('#borges').on('show.bs.collapse', function () {
        $('#cats').hide();
      });
```

a parte `$('#cats').hide();` oculta a section atual
